lyf/adminPanel/urls.py
from django.urls import path
from . import views

app_name='adminPanel'
urlpatterns = [
    path('adminPanel', views.adminPanel, name='adminPanel'),
    path('adminProducts',views.adminProducts,name='adminProducts'),
    path('adminCategory',views.adminCategory,name='adminCategory'),
    path('adminAddCategory',views.adminAddCategory,name='adminAddCategory'),
    path('adminUpdateCategory/<int:id>',views.adminUpdateCategory,name='adminUpdateCategory'),
    path('adminDeleteCategory/<int:id>',views.adminDeleteCategory,name='adminDeleteCategory'),
    path('providerList',views.providerList,name='providerList'),
    path('renterList',views.renterList,name='renterList'),
    path('blockUnblockUserProvider/<int:id>',views.blockUnblockUserProvider,name='blockUnblockUserProvider'),
    path('blockUnblockUserRenter/<int:id>',views.blockUnblockUserRenter,name='blockUnblockUserRenter'),
    path('adminProducts',views.adminProducts,name='adminProducts'),
    path('activeDeactiveProducts/<int:id>',views.activeDeactiveProducts,name='activeDeactiveProducts'),
    path('coupons_page',views.coupons_page,name='coupons_page'),
    path('add_coupons',views.add_coupons,name='add_coupons'),
    path('coupons_activate_deactivate/<int:id>',views.coupons_activate_deactivate,name='coupons_activate_deactivate'),
    path('pay_provider_success/<int:id>',views.pay_provider_success,name='pay_provider_success'),
    path('user_offers',views.user_offers,name='user_offers'),
    path('download_detailed_report',views.download_detailed_report,name='download_detailed_report'),
    path('report_download',views.report_download,name='report_download'),
    path('pay_provider_success/<int:id>/',views.pay_provider_success,name='pay_provider_success'),
    path('order_complete_details/<int:id>',views.order_complete_details,name='order_complete_details'),
    path('product_offer_form/', views.product_offer_form, name='product_offer_form'),
    path('category_offer_form/', views.category_offer_form, name='category_offer_form'),
    path('add_product_offer/', views.add_product_offer, name='add_product_offer'),
    path('add_category_offer/', views.add_category_offer, name='add_category_offer'),
    path('block_unblock_cat/<int:id>',views.block_unblock_cat,name='block_unblock_cat'),
    path('block_unblock_pro/<int:id>',views.block_unblock_pro,name='block_unblock_pro'),
    path('product_searchbar',views.product_searchbar,name='product_searchbar'),
    path('rental_searchbar',views.rental_searchbar,name='rental_searchbar'),
    path('provider_searchbar',views.provider_searchbar,name='provider_searchbar'),
    path('renter_searchbar',views.renter_searchbar,name='renter_searchbar'),

]

lyf/lyf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace='home')),
    path('',include('products.urls',namespace='products')),
    path('',include('user.urls',namespace='user')),
    path('',include('adminPanel.urls',namespace='adminPanel')),
    path('',include('provider.urls',namespace='provider')),
    path('',include('cart.urls',namespace='cart')),
    path('',include('order.urls',namespace='order')),
    path('',include('payments.urls',namespace='payments')),
    path('paypal/', include('paypal.standard.ipn.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyf/order/urls.py
from django.urls import path
from . import views


app_name='order'
urlpatterns = [
    path('confirmRental', views.confirmRental,name='confirmRental'),
    path('rental_management/',views.rental_management,name='rental_management'),
    path('statusChange/<int:id>/',views.statusChange,name='statusChange'),
    path('coupon_apply/<int:id>',views.coupon_apply,name='coupon_apply'),
    path('coupon_clear/<int:id>',views.coupon_clear,name='coupon_clear'),
]

lyf/payments/urls.py
from django.urls import path
from . import views
from paypal.standard.ipn import views as paypal_ipn_views

app_name='payments'
urlpatterns = [
    path('payments/<int:id>',views.make_payments,name='make_payments'),
    path('payment_done/<int:id>',views.payment_done,name='payment_done'),
    path('payment_cancelled',views.payment_cancelled,name='payment_cancelled'),
    path('make_payments/<int:id>/',views.make_payments,name='make_payments'),
    path('final_pay/<int:id>',views.final_pay,name='final_pay'),
    path('wallet',views.wallet,name='wallet'),
    path('wallet_credit/<int:id>/',views.wallet_credit,name='wallet_credit'),
    path('payment_selection/<int:id>',views.payment_selection,name='payment_selection'),
    path('wallet_debit/<int:id>',views.wallet_debit,name='wallet_debit'),
    path('provider_pay/<int:id>/', views.provider_pay, name='provider_pay'),
]

lyf/user/urls.py
from django.urls import path
from . import views

app_name='user'
urlpatterns = [
    path('performlogin', views.performlogin,name='performlogin'),
    path('user_registration', views.user_registration,name='user_registration'),
    path('otpPage',views.otpPage,name='otpPage'),
    path('perform_logout',views.perform_logout,name='perform_logout'),
    path('resendOtp',views.resendOtp,name='resendOtp'),
    path('user_profile/',views.user_profile,name='user_profile'),
    path('user_payment',views.user_payment,name='user_payment'),
    path('user_cancel_rental/<int:id>',views.user_cancel_rental,name='user_cancel_rental'),
    path('user_invoice/<int:id>',views.user_invoice,name='user_invoice'),
    path('password_forget_maiil', views.password_forget_maiil, name='password_forget_maiil'),
    path('forgot_otp_verify',views.forgot_otp_verify,name='forgot_otp_verify'),
    path('password_change',views.password_change,name='password_change'),
    path('user_edit',views.user_edit,name='user_edit'),
    path('user_referral',views.user_referral,name='user_referral'),
]

lyf/adminPanel/views.py
import csv
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect
from .models import Categories, Product, coupons, ProductOffer, CategoryOffer
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from user.models import CustomUser
from order.models import order
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from datetime import datetime
from django.http import HttpResponse, HttpResponseForbidden
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from datetime import datetime
from django.urls import reverse
from django.db.models import Q


def admin_access_required(view_func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            return view_func(request, *args, **kwargs)
        else:
            return HttpResponseForbidden("You don't have permission to access this page.")

    return wrapper
 

@admin_access_required
def adminAddProducts(request):
    pass


@admin_access_required
def adminCategory(request):
    cat = Categories.objects.all()
    return render(request, 'adminPanel/adminCategory.html', {'cat': cat})


@admin_access_required
def adminAddCategory(request):
    if request.method == 'POST':
        Name = request.POST.get('Name').strip()
        description = request.POST.get('Description')
        if not Name:
            messages.error(request, 'Category name is required')
        else:
            Categories.objects.create(Name=Name,description=description)
            messages.success(request, 'Category added successfully')
            return redirect('adminPanel:adminCategory')

    return render(request,'adminPanel/adminAddCategory.html')

@admin_access_required
def adminDeleteCategory(request,id):
    ct=Categories.objects.get(id=id)
    ct.delete()
    return redirect('adminPanel:adminCategory')

@admin_access_required
def adminUpdateCategory(request, id):
    cu = Categories.objects.get(id=id)

    if request.method == 'POST':
        Name = request.POST.get('Name').strip()
        description = request.POST.get('description')

        if Name:
            cu.Name = Name
        if description:
            cu.description = description

        if not Name:
            messages.error(request, 'Invalid data')
        else:
            cu.save()
            return redirect('adminPanel:adminCategory')
    
    return render(request, 'adminPanel/adminUpdateCategory.html', {'cu': cu})


@admin_access_required
def adminProducts(request):
    products=Product.objects.all()
    products_per_page = 10
    paginator = Paginator(products, products_per_page)

    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'adminPanel/adminProducts.html',{'products': products})


@admin_access_required
def renterList(request):
    renters = CustomUser.objects.all().exclude(is_staff=True)
    renters_per_page = 10
    paginator = Paginator(renters, renters_per_page)

    page = request.GET.get('page')
    try:
        renters = paginator.page(page)
    except PageNotAnInteger:
        renters = paginator.page(1)
    except EmptyPage:
        renters = paginator.page(paginator.num_pages)

    return render(request, 'adminPanel/renterList.html', {'renter': renters})

@admin_access_required
def providerList(request):
    provider=CustomUser.objects.filter(is_staff=True).exclude(is_superuser=True)
    provider_per_page = 10
    paginator = Paginator(provider, provider_per_page)

    page = request.GET.get('page')
    try:
        provider = paginator.page(page)
    except PageNotAnInteger:
        provider = paginator.page(1)
    except EmptyPage:
        provider = paginator.page(paginator.num_pages)
        
    return render(request,'adminPanel/providerList.html',{'provider':provider})

@admin_access_required
def blockUnblockUserProvider(request,id=id):
    if request.method == 'POST':
        u=CustomUser.objects.get(id=id)
        if u.is_active==True:
            u.is_active=False
        else:
            u.is_active=True
        u.save()
    return redirect('adminPanel:providerList')

@admin_access_required
def blockUnblockUserRenter(request,id=id):
    if request.method == 'POST':
        u=CustomUser.objects.get(id=id)
        if u.is_active==True:
            u.is_active=False
        else:
            u.is_active=True
        u.save()
    return redirect('adminPanel:renterList')

@admin_access_required
def activeDeactiveProducts(request,id=id):
    if request.method=='POST':
        ban=Product.objects.get(id=id)
        if ban.is_active==True:
            ban.is_active=False
        else:
            ban.is_active=True
        ban.save()
    return redirect('adminPanel:adminProducts')


@admin_access_required
def user_offers(request):
    return render(request,'adminPanel/adminPanel_offers.html')


@admin_access_required
def coupons_page(request):
    cop=coupons.objects.all()
    return render(request,'adminPanel/admin_coupons.html',{'cop':cop})

@admin_access_required
def add_coupons(request):
    COUPON_CHOICE = coupons.COUPON_CHOICE
    if request.method == 'POST':
        coupon_type=request.POST.get('coupon_type')
        name = request.POST.get('name').strip()
        discount = request.POST.get('discount')
        num = request.POST.get('num')
        if not name or not discount:
            messages.error(request, 'Please provide correct details')
        else:
            obj=coupons.objects.create(name=name,discount=discount,num=num,coupon_type=coupon_type)
            messages.success(request, 'Coupouns added successfully')
            return redirect('adminPanel:coupons_page')
    return render(request,'adminPanel/add_coupons.html',{'COUPON_CHOICE': COUPON_CHOICE })


@admin_access_required
def coupons_activate_deactivate(request,id):
    if request.method=='POST':
        cop=coupons.objects.get(id=id)
        if cop.is_active:
            cop.is_active=False
        else:
            cop.is_active=True
    cop.save()
    return redirect('adminPanel:coupons_page')



@admin_access_required
def adminPanel(request, chart_labels=None, chart_data=None, chart_labels_month=None, chart_data_month=None):
    orders = order.objects.all()

    orders_by_month = {}
    orders_by_year = {}
    orders_by_day = {}

    for o in orders:
        month = o.date.month
        if month in orders_by_month:
            orders_by_month[month] += o.quantity
        else:
            orders_by_month[month] = o.quantity

        year = o.date.year
        if year in orders_by_year:
            orders_by_year[year] += o.quantity
        else:
            orders_by_year[year] = o.quantity

        day = o.date.day
        if day in orders_by_day:
            orders_by_day[day] += o.quantity
        else:
            orders_by_day[day] = o.quantity

    detailed_report = None

    if request.method == 'POST':
        report = request.POST.get('status')

        if report == 'yearly':
            chart_labels = list(orders_by_year.keys())
            chart_data = list(orders_by_year.values())
            detailed_report = order.objects.filter(date__year=datetime.now().year)

        elif report == 'monthly':
            chart_labels = list(orders_by_month.keys())
            chart_data = list(orders_by_month.values())
            detailed_report = order.objects.filter(date__month=datetime.now().month)

        elif report == 'daily':
            chart_labels = list(orders_by_day.keys())
            chart_data = list(orders_by_day.values())
            detailed_report = order.objects.filter(date=datetime.now().date())

    return render(request, 'adminPanel/adminPanel.html', {'chart_labels': chart_labels, 'chart_data': chart_data, 'detailed_report': detailed_report})



@admin_access_required
def download_detailed_report(request):
    if request.method=='POST':
        status = request.POST.get('status')
        print('status',status)
        orders = None
        if status == 'yearly':
            orders = order.objects.filter(date__year=datetime.now().year)
        elif status == 'monthly':
            orders = order.objects.filter(date__month=datetime.now().month)
        elif status == 'daily':
            orders = order.objects.filter(date=datetime.now().date())

        
        
        request.session['status']=status

        if orders:
            return render(request, 'adminPanel/adminPanel_report.html', {'orders': orders})
        else:
            return render(request, 'adminPanel/adminPanel_report.html')
    
@admin_access_required
def report_download(request):
    template = get_template('adminPanel/adminPanel_report.html')
    status=request.session['status']
    if status == 'yearly':
        orders = order.objects.filter(date__year=datetime.now().year)
    elif status == 'monthly':
        orders = order.objects.filter(date__month=datetime.now().month)
    elif status == 'daily':
        orders = order.objects.filter(date=datetime.now().date())
    context={
            'orders':orders,
        }
    
    html = template.render(context)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="your_pdf_filename.pdf"'

    # Create a PDF object
    pisa_status = pisa.CreatePDF(html, dest=response)

    # If there are any error messages, show them
    if pisa_status.err:
        return HttpResponse('We had some errors with code %s <pre>%s</pre>' % (pisa_status.err, html))

    return response


@admin_access_required
def pay_provider_success(request,id):
    ord=order.objects.get(id=id)
    ord.payment_provider=True
    ord.save()

lyf/templates/adminPanel/add_category_offer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add category offer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" >

</head>
<body>
    
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Add category offer</h2>
                </div>
                <div class="card-body">
                    {% if messages %}
                        <div class="alert alert-danger">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    {% endif %}

                    <form method="post" action="{% url 'adminPanel:add_category_offer' %}">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="category" class="form-label">Select Category</label>
                            <select name="category" class="form-control" id="category">
                                {% for cat in categories %}
                                <option value="{{ cat.id }}">{{ cat.Name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                
                        <label for="discount_percentage">Discount Percentage:</label>
                        <input type="number" name="discount_percentage" step="0.01" required><br><br>
                
                        <label for="start_date">Start Date:</label>
                        <input type="date" name="start_date" required><br><br>
                
                        <label for="end_date">End Date:</label>
                        <input type="date" name="end_date" required><br><br>
                
                        <button class="btn btn-secondary" type="submit">Add Offer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

lyf/templates/adminPanel/add_coupons.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Admin - Add coupons</title>
</head>
<body>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Add Coupons</h2>
                </div>
                <div class="card-body">
                    {% if messages %}
                        <div class="alert alert-danger">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    {% endif %}

                    <form method="post" action="{% url 'adminPanel:add_coupons' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="coupon_type" class="label">Type:</label>
                            <select name="coupon_type" id="coupon_type">
                                {% for choice in COUPON_CHOICE %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == i.status %}selected{% endif %}>
                                        {{ choice.1 }}
                                    </option>
                                {% endfor %}
                            </select><br>
                            <label for="name" class="form-label">Coupons Name:</label><br>
                            <input type="text" class="form-control" id="name" name="name" required>
                            <label for="num" class="form-label">Number of Coupons:</label>
                            <input type="number" class="form-control" id="num" name="num" required>
                            <label for="discount" class="form-label">Discount:</label><br>
                            <input type="number" class="form-control" id="discount" name="discount"  required></input>
                        </div>
                        <button type="submit" class="btn btn-primary">Add Coupon</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-pzjw8/Nv3pIVuPphJtYWB9Lk3m6Hg3eELx5WqlRmSCAEe3sBThb6hqRI3OkJlNIH6" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js" integrity="sha384-XihSBy5XsVGkBcFFh4G8kCiT6nBFWyRpgGBPHLmVqBRL5iK3wFjAfiJBI5hUJwSw" crossorigin="anonymous"></script>

</body>
</html>

lyf/templates/adminPanel/adminRentalDetails.html
{% extends 'adminPanel/adminPanel.html' %}
{% block content %}

<div
      id="TopMenu"
      class="sidebar bg-white d-block d-md-none"
      style="margin-top: 10rem"
    >
      <div class="position-sticky">
        <div class="list-group list-group-flush">
          <a
            href="{% url 'adminPanel:adminPanel' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-tachometer-alt fa-fw me-3"></i
            ><span>Dashboard</span>
          </a>
          <a
            href="{% url 'adminPanel:adminProducts' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-area fa-fw me-3"></i><span>Products</span>
          </a>
          <a
            href="{% url 'order:rental_management' %}"
            class="list-group-item list-group-item-action py-2 ripple active"
          >
            <i class="fas fa-lock fa-fw me-3"></i><span>Rental Details</span>
          </a>
          <a
            href="{% url 'adminPanel:adminCategory' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i><span>Category</span>
          </a>
          <a
            href="{% url 'adminPanel:product_offer_form' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i
            ><span>Product Offers</span>
          </a>
          <a
            href="{% url 'adminPanel:category_offer_form' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i
            ><span>Category Offers</span>
          </a>
          <a
            href="{% url 'adminPanel:coupons_page' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i><span>Coupons</span>
          </a>
          <a
            href="{% url 'adminPanel:providerList' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i><span>Providers</span>
          </a>
          <a
            href="{% url 'adminPanel:renterList' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i><span>Renters</span>
          </a>
        </div>
      </div>
    </div>
    <div id="sidebarMenu" class="sidebar bg-white d-none d-md-block">
      <div class="position-sticky">
        <div class="list-group list-group-flush">
          <a
            href="{% url 'adminPanel:adminPanel' %}"
            class="list-group-item list-group-item-action py-2 ripple "
          >
            <i class="fas fa-tachometer-alt fa-fw me-3"></i
            ><span>Dashboard</span>
          </a>
          <a
            href="{% url 'adminPanel:adminProducts' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-area fa-fw me-3"></i><span>Products</span>
          </a>
          <a
            href="{% url 'order:rental_management' %}"
            class="list-group-item list-group-item-action py-2 ripple active"
          >
            <i class="fas fa-lock fa-fw me-3"></i><span>Rental Details</span>
          </a>
          <a
            href="{% url 'adminPanel:adminCategory' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i><span>Category</span>
          </a>
          <a
            href="{% url 'adminPanel:product_offer_form' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i
            ><span>Product Offers</span>
          </a>
          <a
            href="{% url 'adminPanel:category_offer_form' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i
            ><span>Category Offers</span>
          </a>
          <a
            href="{% url 'adminPanel:coupons_page' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i><span>Coupons</span>
          </a>
          <a
            href="{% url 'adminPanel:providerList' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i><span>Providers</span>
          </a>
          <a
            href="{% url 'adminPanel:renterList' %}"
            class="list-group-item list-group-item-action py-2 ripple"
          >
            <i class="fas fa-chart-line fa-fw me-3"></i><span>Renters</span>
          </a>
        </div>
      </div>
    </div>

<div id="productContent"
class="container d-flex flex-column"
style="max-width: 600px; height: 700px; margin-top: 120px">
    <h1 class="text-2xl">Rental Details</h1><br>
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <form class="form-inline" method="get" action="{% url 'adminPanel:rental_searchbar' %}">
    
      <div class="input-group rounded">
        {% if query %}
        <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" name="q" value="{{query}}"/>
        {% else %}
        <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" name="q"/>
        {% endif %}
        <button type="submit" class="btn btn-transparent"><span class="input-group-text border-0" id="search-addon">
          <i class="bi bi-search"></i>
        </span></button>
      </div>
      </form>
    <ul class="list-group">
        {% for i in ord %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between">
                    <div>
                        <h4 class="mb-1">Product: {{ i.product }}</h4>
                        <p class="mb-1">Quantity: {{ i.quantity }}</p> 
                        <p class="mb-1">Days required: {{ i.days_needed }}</p>
                        <p class="mb-1">Distance: {{ i.distance|floatformat:2 }} km</p>
                    </div>
                    <div class="col d-flex flex-column align-items-end">
                        <span class="mb-2" style="color: #000000;">Total price: ₹{{ i.total_price }}</span>
                        <div class="footer">
                            {% if i.payment %}
                                <!-- your_template.html -->
                                <form method="post" action="{% url 'order:statusChange' i.id %}">
                                    {% csrf_token %}
                                    <div class="row g-2 align-items-center">
                                        <div class="col-auto">
                                            <label for="status" class="label me-2">Status:</label>
                                        </div>
                                        <div class="col-auto">
                                            <select name="status" id="status" class="form-select">
                                                {% for choice in i.STATUS_CHOICES %}
                                                    <option value="{{ choice.0 }}" {% if choice.0 == i.status %}selected{% endif %}>
                                                        {{ choice.1 }}
                                                    </option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="col-auto">
                                            <button type="submit" class="btn btn-success" style="margin-top: -15px;">Save</button>
                                        </div>
                                    </div>
                                </form>
                                
                                {% if i.payment_provider %}
                                    <button class="btn btn-danger hover" style="margin-left: 10px;">Payment completed</button>
                                {% else %}
                                    <a href="{% url 'payments:provider_pay' i.id %}" class="btn btn-danger" style="margin-left: 10px;">Pay to Provider</a>
                                {% endif %}
                            {% else %}
                                <a href="" class="btn btn-block">Not Confirmed</a>
                            {% endif %}
                            <a href="{% url 'adminPanel:order_complete_details' i.id %}" class="btn btn-info" style="margin-left: 10px;">Details</a>
                        </div>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <div class="pagination mt-4">
        <span class="step-links">
            {% if ord.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ ord.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ ord.number }} of {{ ord.paginator.num_pages }}.
            </span>
    
            {% if ord.has_next %}
                <a href="?page={{ ord.next_page_number }}">next  </a>
                <a href="?page={{ ord.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}