lyf/lyf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace='home')),
    path('',include('products.urls',namespace='products')),
    path('',include('user.urls',namespace='user')),
    path('',include('adminPanel.urls',namespace='adminPanel')),
    path('',include('provider.urls',namespace='provider')),
    path('',include('cart.urls',namespace='cart')),
    path('',include('order.urls',namespace='order')),
    path('',include('payments.urls',namespace='payments')),
    path('paypal/', include('paypal.standard.ipn.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyf/provider/urls.py
from django.urls import path
from . import views

app_name='provider'
urlpatterns = [
    path('providerPanel/', views.providerPanel,name='providerPanel'),
    path('providerAddProducts',views.providerAddProduct,name='providerAddProducts'),
    path('providerUpdateProducts/<int:id>',views.providerUpdateProducts,name='providerUpdateProducts'),
    path('providerDeleteProducts/<int:id>',views.providerDeleteProducts,name='providerDeleteProducts'),
    path('providerApproval',views.providerApproval,name='providerApproval'),
    path('activateOrder/<int:id>',views.activateOrder,name='activateOrder'),  
    path('deleteOrder/<int:id>',views.deleteOrder,name='deleteOrder'),
    path('provider_details/',views.provider_details,name='provider_details'),
    path('reactivate_product/<int:id>',views.reactivate_product,name='reactivate_product'),
    path('cancelOrder/<int:id>',views.cancelOrder,name='cancelOrder'),
    path('provider_payments',views.provider_payments,name='provider_payments'),

]

lyf/provider/models.py
from django.db import models
from adminPanel.models import Product
from user.models import CustomUser

# Create your models here.

class provider_credentials(models.Model):
    provider=models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    pan_card=models.CharField(max_length=35,null=False)
    pan_photo=models.ImageField(upload_to='uploads/provider/',blank=True,null=True)
    paypal_id=models.EmailField(null=False)
    

lyf/provider/views.py
from django.shortcuts import render,redirect
from adminPanel.models import Categories
from adminPanel.models import Product
from user.views import performlogin
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseBadRequest
from adminPanel.models import multipleImage
from django.core.mail import send_mail
from user.models import CustomUser
from django import http
from order.models import order
from .models import provider_credentials
from adminPanel.models import Product
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages



@login_required(login_url='user:performlogin')
def providerPanel(request):
    user=request.user
    try:
        pro_cred=provider_credentials.objects.get(provider=user)
        if pro_cred:
            product=Product.objects.all()
            return render(request,'provider/providerPanel.html',{'product':product})
    except:
        messages.error(request,'Please add your details')
        return redirect('provider:provider_details')


def create_security(given_price):
    price = int(given_price)
    if price>100:
        x=price*5
        return x
    else:
        x=price*10
        return x


@login_required(login_url='user:performlogin')
def providerAddProduct(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        price = request.POST.get('price')
        category_Name = request.POST.get('category')
        quantity = request.POST.get('quantity')
        phone=request.POST.get('phone')
        address=request.POST.get('address')
        street=request.POST.get('street')
        city=request.POST.get('city')
        state=request.POST.get('state')
        pincodePro = request.POST.get('pincodePro')

        # Handle main image upload
        main_image = request.FILES.get('image') if 'image' in request.FILES else None

        # Handle multiple images upload
        additional_images = request.FILES.getlist('images')

        # Assuming you have a Categories model with an id field
        category = Categories.objects.get(Name=category_Name)

        security=create_security(price)
        # Create the product
        product = Product.objects.create(
            user=request.user,
            category=category,
            title=title,
            description=description,
            price=price,
            image=main_image,
            quantity=quantity,
            pincodePro = pincodePro,
            phone = phone,
            address = address,
            street = street,
            city = city,
            state = state,
            security = security,
        )

        # Create MultipleImage instances for additional images
        for img in additional_images:
            multipleImage.objects.create(product=product, image=img)

        user = request.user
        if user.is_staff == False:
            user.is_staff = True
            user.save()
        
        
        return redirect('provider:providerPanel')  # Redirect to the provider panel after adding a product

    # Fetch categories from the database
    categories = Categories.objects.all()

    return render(request, 'provider/providerAddproducts.html', {'categories': categories})
    return render(request, 'provider/providerAddproducts.html', {'categories': categories})


@login_required(login_url='user:performlogin')
def providerDeleteProducts(request,id):
    pro=Product.objects.get(id=id)
    pro.delete()
    return redirect('provider:providerPanel')


@login_required(login_url='user:performlogin')
def providerUpdateProducts(request, id):
    # Get the product instance using the product_id
    product = get_object_or_404(Product, id=id)

    if request.method == 'POST':
        # Process the form submission
        title = request.POST.get('title').strip()
        description = request.POST.get('description').strip()
        price = request.POST.get('price').strip()
        image = request.FILES.get('image') if 'image' in request.FILES else None
        pincodePro = request.POST.get('pincodePro').strip()
        # Update the product fields
        product.title = title
        product.description = description
        product.price = price
        product.pincodePro = pincodePro

        if image:
            product.image = image

        product.save()
        
        return redirect('provider:providerPanel')  # Redirect to the provider panel or any other desired page

    return render(request, 'provider/providerUpdateProducts.html', {'product': product})


@login_required(login_url='user:performlogin')
def providerApproval(request):
    ord = order.objects.filter(product__user=request.user).order_by('-date')
    #total_price = ord.product.price * ord.quantity * ord.days_needed
    context={
        'ord':ord
    }
    return render(request, 'provider/providerApproval.html', context)


@login_required(login_url='user:performlogin')
def activateOrder(request,id):
    ord = order.objects.get(id=id)
    ord.is_active=True
    subject = 'Rental Confirmation'
    message = f'Rental Confirmed for "{ord.product}". Please login to your user profile to make payments.'
    from_email = 'o23211671@gmail.com'  
    email = ord.user
    send_mail(subject, message, from_email, [email])
    ord.status='confirmed'
    ord.save()
    return redirect(reverse('provider:providerApproval'))


@login_required(login_url='user:performlogin')
def deleteOrder(request,id):
    ord = order.objects.get(id=id)
    ord.delete()
    return redirect(reverse('provider:providerApproval'))


@login_required(login_url='user:performlogin')
def reactivate_product(request,id):
    ord=order.objects.get(id=id)
    quan=ord.quantity
    pro=ord.product.id
    product_instance=Product.objects.get(id=pro)
    product_instance.quantity += quan
    product_instance.save()
    if product_instance.rentable==False:
        product_instance.rentable=True
    product_instance.save()
    ord.status='completed'
    ord.save()
    print(product_instance.quantity)
    print(product_instance.rentable)
    return redirect('provider:providerApproval')


@login_required(login_url='user:performlogin')
def provider_details(request):
    provider_instance_set=None
    try:
        provider_instance_set = get_object_or_404(provider_credentials, provider=request.user)
        print(provider_instance_set)
    except:
        provider_instance_set=None

    if request.method == 'POST':
        pan_number = request.POST.get('pan_number').strip()
        pan_image = request.FILES.get('pan_image') if 'pan_image' in request.FILES else None
        paypal_mail = request.POST.get('paypal_mail')
        print(pan_image)


        if provider_instance_set:
            provider_instance_set.pan_card = pan_number
            provider_instance_set.pan_photo = pan_image
            provider_instance_set.paypal_id = paypal_mail

            if pan_image:
                provider_instance_set.pan_photo=pan_image
            provider_instance_set.save()
            messages.success(request,'Provider details updated')

            return redirect('provider:provider_details')
        else:
            provider_credentials.objects.create(
                provider=request.user,
                pan_card=pan_number,
                pan_photo=pan_image,
                paypal_id=paypal_mail,
            )
            messages.success(request,'Provider details added')
            return redirect('provider:provider_details')


    return render(request, 'provider/provider_details.html', {'provider_instance_set': provider_instance_set})


def cancelOrder(request,id):
    ord=order.objects.get(id=id)
    ord.status='cancelled'
    ord.save()
    return redirect('provider:providerApproval')


def provider_payments(request):
    user = request.user
    ord = order.objects.filter(product__user=user, payment_provider=True)
    return render(request,'provider/provider_payments.html',{'ord':ord})

lyf/templates/provider/providerApproval.html
{% extends "homePage.html" %}

{% block content %}

<style>
    body {
        background-color: #ffffff;
    }

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #C1DCDC;
  overflow-x: hidden;
  padding-top: 20px;
  padding-top: 130px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 20px;
  color: black;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 20px; /* Increased text to enable scrolling */
  padding: 0px 50px 100px;
  padding-top: 20px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

.active {
    background-color: white;
}

.list-group-item{
    background-color: #f1f1f1;
}


</style>

<div class="sidenav">
    <a href="{% url 'provider:providerPanel' %}">Products</a>
    <a href="{% url 'provider:provider_details' %}" >Profile</a>
    <a href="{% url 'provider:providerApproval' %}" class="active" >Rentals</a>
</div>


<div class="main" style="margin-top: 8rem;">
    <h1 class="text-2xl">Rental Confirmation</h1><br>
    <ul class="list-group">
        {% for i in ord %}
        <li class="list-group-item">
            <div class="d-flex justify-content-between">
                <div>
                    <h4 class="mb-1">Product: {{ i.product }}</h4>
                    <p class="mb-1">Quantity: {{ i.quantity }}</p> 
                    <p class="mb-1">Days required: {{ i.days_needed }}</p>
                    <p class="mb-1"><b>Status: {{ i.status }}</b></p>
                    
                </div>
                <div class="col d-flex flex-column align-items-end">
                    <span class="mb-2" style="color: #000000;">Total price: ₹{{ i.total_price }}</span>

                    <div class="footer">
                        {% if i.is_active %}
                            {% if i.status == 'returned' or i.status == 'cancelled' %}
                                <a href="{% url 'provider:reactivate_product' i.id %}" class="btn btn-outline-warning">Reacitvate</a>
                            {% endif %}
                        {% else %}
                            {% if i.status == 'cancelled' %}
                            <button href="" class="btn btn-danger">cancelled</button>
                            {% else %}
                            <a href="{% url 'provider:activateOrder' i.id %}" class="btn btn-outline-success">Confirm Rental</a>
                            <a href="{% url 'provider:cancelOrder' i.id %}" class="btn btn-outline-danger">Cancel Rental</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </li><br>
        {% endfor %}
    </ul>
</div>

{% endblock %}

lyf/templates/provider/providerPanel.html
{% extends "homePage.html" %} {% block content %}
<style>
  body {
    background-color: #ffffff;
  }

  .sidenav {
    height: 100%;
    width: 160px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #c1dcdc;
    overflow-x: hidden;
    padding-top: 20px;
    padding-top: 130px;
  }

  @media (max-width: 768px) {
    .sidenav {
      width: 70px;
    }
  }
  
  .sidenav a {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 20px;
    color: black;
    display: block;
  }

  .sidenav a:hover {
    color: #f1f1f1;
  }

  .main {
    margin-left: 160px; /* Same as the width of the sidenav */
    font-size: 20px; /* Increased text to enable scrolling */
    padding: 0px 50px 100px;
    padding-top: 20px;
  }
  @media (max-width: 768px) {
    .main {
      margin-left: 60px;
    }
  }
  @media screen and (max-height: 450px) {
    .sidenav {
      padding-top: 15px;
    }
    .sidenav a {
      font-size: 18px;
    }
  }

  .active {
    background-color: white;
  }
  .list-group-item {
    background-color: #f1f1f1;
  }
</style>

<div class="sidenav">
  <a href="{% url 'provider:providerPanel' %}" class="active d-flex">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="32"
      height="32"
      fill="currentColor"
      class="bi bi-bag-check-fill"
      viewBox="0 0 16 16"
    >
      <path
        fill-rule="evenodd"
        d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0m-.646 5.354a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0z"
      />
    </svg>
    <span class="d-none d-md-block">Products</span>
  </a>
  <a href="{% url 'provider:provider_details' %}" class="d-flex">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="32"
      height="32"
      fill="currentColor"
      class="bi bi-person"
      viewBox="0 0 16 16"
    >
      <path
        d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"
      />
    </svg>
    <span class="d-none d-md-block">Profile</span></a
  >
  <a href="{% url 'provider:providerApproval' %}" class="d-flex">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="32"
      height="32"
      fill="currentColor"
      class="bi bi-hand-thumbs-up-fill"
      viewBox="0 0 16 16"
    >
      <path
        d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a10 10 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733q.086.18.138.363c.077.27.113.567.113.856s-.036.586-.113.856c-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.2 3.2 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.8 4.8 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"
      />
    </svg>
    <span class="d-none d-md-block">Rentals</span></a
  >
  <a href="{% url 'provider:provider_payments' %}" class="d-flex">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="32"
      height="32"
      fill="currentColor"
      class="bi bi-cash-coin"
      viewBox="0 0 16 16"
    >
      <path
        fill-rule="evenodd"
        d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8m5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0"
      />
      <path
        d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195z"
      />
      <path
        d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083q.088-.517.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1z"
      />
      <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 6 6 0 0 1 3.13-1.567" />
    </svg>
    <span class="d-none d-md-block">Payments</span></a
  >
</div>

<div class="main" style="margin-top: 8rem">
  <h1 class="text-2xl">My Products</h1>
  <a
    href="{% url 'provider:providerAddProducts' %}"
    class="btn btn-primary mt-2"
    >Add Products</a
  ><br />

  {% if request.user.products.all %}
  <ul class="list-group" style="margin: 10px">
    {% for product in request.user.products.all %}
    <li class="list-group-item">
      <div class="row">
        <div class="col-md-4">
          {% if product.image %}
          <img
            src="{{ product.image.url }}"
            class="img-fluid rounded-start img-thumbnail"
            style="width: 100%; max-width: 150px; max-height: 100px"
            alt="{{ product.title }}"
          />
          {% else %}
          <p>No image available</p>
          {% endif %}
        </div>
        <div class="col-md-8" style="padding-top: 20px">
          <h5>{{ product.title }}</h5>
          <div class="d-flex flex-column justify-content-between align-items-center">
            <p>{{ product.description }}</p>
            <p>Price: ₹{{ product.price }}</p>
            <div class="btn-group" role="group">
              <a
                href="{% url 'provider:providerDeleteProducts' product.id %}"
                class="btn btn-danger mb-2"
                >Delete</a
              >
              <a
                href="{% url 'provider:providerUpdateProducts' product.id%}"
                class="btn btn-primary mb-2"
                >Update</a
              >
            </div>
            <!-- Add more details as needed -->
          </div>
        </div>
      </div>
    </li>
    <br />
    {% endfor %}
  </ul>

  {% else %}
  <div class="alert alert-info mt-4">You don't have any products yet...</div>
  {% endif %}
</div>
{% endblock %}

lyf/templates/provider/provider_payments.html
{% extends "homePage.html" %}
{% load static %}
{% block content %}

<style>
    body {
      background-color: #ffffff;
    }
  
    .sidenav {
      height: 100%;
      width: 160px;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #c1dcdc;
      overflow-x: hidden;
      padding-top: 20px;
      padding-top: 130px;
    }
  
    @media (max-width: 768px) {
      .sidenav {
        width: 70px;
      }
    }
    
    .sidenav a {
      padding: 6px 8px 6px 16px;
      text-decoration: none;
      font-size: 20px;
      color: black;
      display: block;
    }
  
    .sidenav a:hover {
      color: #f1f1f1;
    }
  
    .main {
      margin-left: 160px; /* Same as the width of the sidenav */
      font-size: 20px; /* Increased text to enable scrolling */
      padding: 0px 50px 100px;
      padding-top: 20px;
    }
    @media (max-width: 768px) {
      .main {
        margin-left: 60px;
      }
    }
    @media screen and (max-height: 450px) {
      .sidenav {
        padding-top: 15px;
      }
      .sidenav a {
        font-size: 18px;
      }
    }
  
    .active {
      background-color: white;
    }
    .list-group-item {
      background-color: #f1f1f1;
    }
  </style>

<div class="sidenav">
    <a href="{% url 'provider:providerPanel' %}" class="d-flex">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        fill="currentColor"
        class="bi bi-bag-check-fill"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0m-.646 5.354a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0z"
        />
      </svg>
      <span class="d-none d-md-block">Products</span>
    </a>
    <a href="{% url 'provider:provider_details' %}" class="d-flex">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        fill="currentColor"
        class="bi bi-person"
        viewBox="0 0 16 16"
      >
        <path
          d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"
        />
      </svg>
      <span class="d-none d-md-block">Profile</span></a
    >
    <a href="{% url 'provider:providerApproval' %}" class="d-flex">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        fill="currentColor"
        class="bi bi-hand-thumbs-up-fill"
        viewBox="0 0 16 16"
      >
        <path
          d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a10 10 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733q.086.18.138.363c.077.27.113.567.113.856s-.036.586-.113.856c-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.2 3.2 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.8 4.8 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"
        />
      </svg>
      <span class="d-none d-md-block">Rentals</span></a
    >
    <a href="{% url 'provider:provider_payments' %}" class="active d-flex">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        fill="currentColor"
        class="bi bi-cash-coin"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8m5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0"
        />
        <path
          d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195z"
        />
        <path
          d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083q.088-.517.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1z"
        />
        <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 6 6 0 0 1 3.13-1.567" />
      </svg>
      <span class="d-none d-md-block">Payments</span></a
    >
  </div>

<div class="main" style="margin-top: 8rem;">
    {% if ord %}
    <h1 class="text-2xl">Payments</h1><br>
    <ul class="list-group">
        {% for i in ord %}
        <li class="list-group-item">
            <div class="d-flex justify-content-between">
                <div>
                    <h4 class="mb-1">Product: {{ i.product }}</h4>
                    <p class="mb-1">Quantity: {{ i.quantity }}</p> 
                    <p class="mb-1">Days required: {{ i.days_needed }}</p>
                    <p class="mb-1"><b>Status: {{ i.status }}</b></p>
                    
                </div>
                <div class="col d-flex flex-column align-items-end">
                    <span class="mb-2" style="color: #000000;">Total price: ₹{{ i.total_price }}</span>

                    <div class="footer">
                        {% if i.is_active %}
                            {% if i.status == 'returned' or i.status == 'cancelled' %}
                                <a href="{% url 'provider:reactivate_product' i.id %}" class="btn btn-outline-warning">Reacitvate</a>
                            {% endif %}
                        {% else %}
                            {% if i.status == 'cancelled' %}
                            <button href="" class="btn btn-danger">cancelled</button>
                            {% else %}
                            <a href="{% url 'provider:activateOrder' i.id %}" class="btn btn-outline-success">Confirm Rental</a>
                            <a href="{% url 'provider:cancelOrder' i.id %}" class="btn btn-outline-danger">Cancel Rental</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </li><br>
        {% endfor %}
    </ul>
    {% else %}
    <div class="card-title mb-4 d-flex align-items-center justify-content-center" style="margin-top: 2rem; width: 200px; height: 150px; margin-left: 180px;">
        <img src="{% static 'image/no_payment.jpg' %}" alt="empty cart image" class="img-fluid" style="width: 100%; height: 100%;">
    </div>    
    
    {% endif %}
</div>

{% endblock %}