lyf/lyf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace='home')),
    path('',include('products.urls',namespace='products')),
    path('',include('user.urls',namespace='user')),
    path('',include('adminPanel.urls',namespace='adminPanel')),
    path('',include('provider.urls',namespace='provider')),
    path('',include('cart.urls',namespace='cart')),
    path('',include('order.urls',namespace='order')),
    path('',include('payments.urls',namespace='payments')),
    path('paypal/', include('paypal.standard.ipn.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyf/payments/urls.py
from django.urls import path
from . import views
from paypal.standard.ipn import views as paypal_ipn_views

app_name='payments'
urlpatterns = [
    path('payments/<int:id>',views.make_payments,name='make_payments'),
    path('payment_done/<int:id>',views.payment_done,name='payment_done'),
    path('payment_cancelled',views.payment_cancelled,name='payment_cancelled'),
    path('make_payments/<int:id>/',views.make_payments,name='make_payments'),
    path('final_pay/<int:id>',views.final_pay,name='final_pay'),
    path('wallet',views.wallet,name='wallet'),
    path('wallet_credit/<int:id>/',views.wallet_credit,name='wallet_credit'),
    path('payment_selection/<int:id>',views.payment_selection,name='payment_selection'),
    path('wallet_debit/<int:id>',views.wallet_debit,name='wallet_debit'),
    path('provider_pay/<int:id>/', views.provider_pay, name='provider_pay'),
]

lyf/user/urls.py
from django.urls import path
from . import views

app_name='user'
urlpatterns = [
    path('performlogin', views.performlogin,name='performlogin'),
    path('user_registration', views.user_registration,name='user_registration'),
    path('otpPage',views.otpPage,name='otpPage'),
    path('perform_logout',views.perform_logout,name='perform_logout'),
    path('resendOtp',views.resendOtp,name='resendOtp'),
    path('user_profile/',views.user_profile,name='user_profile'),
    path('user_payment',views.user_payment,name='user_payment'),
    path('user_cancel_rental/<int:id>',views.user_cancel_rental,name='user_cancel_rental'),
    path('user_invoice/<int:id>',views.user_invoice,name='user_invoice'),
    path('password_forget_maiil', views.password_forget_maiil, name='password_forget_maiil'),
    path('forgot_otp_verify',views.forgot_otp_verify,name='forgot_otp_verify'),
    path('password_change',views.password_change,name='password_change'),
    path('user_edit',views.user_edit,name='user_edit'),
    path('user_referral',views.user_referral,name='user_referral'),
]

lyf/user/models.py
import string
import random
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils import timezone
from django.core.validators import RegexValidator, MinLengthValidator, MaxLengthValidator


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)



class CustomUser(AbstractBaseUser, PermissionsMixin):

    phone_number_validator = RegexValidator(
        regex=r'^\d{1,15}$',  # This regex allows 1 to 15 digits
        message='Phone number must contain only digits.',
        code='invalid_phone_number'
    )

    password_validator = RegexValidator(
        regex=r'^(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$',
        message='Password must contain at least one number and one special character. It should be at least 8 characters long.',
        code='invalid_password'
    )

    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30,null=True)
    phone_number = models.CharField(
        max_length=15,
        blank=True,
        null=True,
        validators=[phone_number_validator]
    )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_super = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    referrer = models.ForeignKey('self',on_delete=models.SET_NULL,null=True,blank=True,related_name='referred_users')
    referral_code = models.CharField(max_length=10,unique=True,blank=True,null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name','phone_number']

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_short_name(self):
        return self.first_name
    
    def generate_referral_code(self):
        characters = string.ascii_letters + string.digits
        return ''.join(random.choice(characters) for i in range(10))
    
    def save(self,*args, **kwargs):
        if not self.referral_code:
            self.referral_code = self.generate_referral_code()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

# Add related_name to avoid clashes with auth.User
CustomUser._meta.get_field('groups').remote_field.related_name = 'customuser_groups'
CustomUser._meta.get_field('user_permissions').remote_field.related_name = 'customuser_permissions'



class userAddress(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    addressType = models.CharField(max_length=10)
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    address = models.CharField(max_length=50,null=False)
    street = models.CharField(max_length=50,null=False)
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    state= models.CharField(max_length=50,null=False)
    pincode = models.CharField(max_length=10,null=False)

    def __str__(self) -> str:
        return self.user.first_name
    

lyf/user/views.py
# views.py
import re
import pyotp
from django.shortcuts import render, redirect
from django.contrib import messages
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from .models import CustomUser
from django.urls import reverse
from pyotp import TOTP
from django.core.mail import send_mail
from datetime import datetime, timedelta  # Import datetime and timedelta
from django.contrib.auth.decorators import login_required
from order.models import order
from payments.models import user_wallet

CustomUser = get_user_model()


def performlogin(request):
    if request.user.is_authenticated:
        if request.user.is_super:
            return redirect('adminPanel:adminPanel')
        else:
            return redirect('home:homePage')
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)

        if user is not None:
            if user.is_superuser:
                login(request, user)
                return redirect("adminPanel:adminPanel")
            else:
                login(request, user)
                return redirect("home:homePage")
        else:
            messages.error(request, 'Invalid login credentials or your are not authorised to access this page')

    return render(request, 'user/performlogin.html')


def user_registration(request):
    if request.user.is_authenticated:
        return redirect('home:homePage')
    class RegistrationForm(forms.ModelForm):
        password1 = forms.CharField(widget=forms.PasswordInput, label='Password')
        password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

        referrer_code = forms.CharField(required=False)

        class Meta:
            model = CustomUser
            fields = ['email', 'first_name', 'last_name', 'phone_number','referrer_code']

        def clean_password2(self):
            password1 = self.cleaned_data.get("password1")
            password2 = self.cleaned_data.get("password2")
            if password1 == password2 and len(password1)>=8 and re.match(r'^(?=.*\d)(?=.*[@$!%*?&])', password1):
                request.session['password'] = password2 
            else:
                raise forms.ValidationError("Your password doesn't meet eligibility criteria.")
            return password2

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            
            referrer_code = form.cleaned_data['referrer_code']

            if referrer_code:
                try:
                    referrer_user=CustomUser.objects.get(referral_code=referrer_code)
                    referrer_id = referrer_user.id
                    request.session['referrer_id']=referrer_id

                except:
                    messages.error(request,'Invalid referral')


            #otp section
            totp = pyotp.TOTP(pyotp.random_base32(), interval=60)
            otp = totp.now()
            request.session["otp_secret_key"] = totp.secret
            valid_date = datetime.now() + timedelta(seconds=60)
            request.session["otp_valid_date"] = str(valid_date)


            #store user details temporarily
            request.session['user_details'] = {
                'email': user.email,
                'first_name': user.first_name,
                'last_name': user.last_name,
                'phone_number': user.phone_number,
                'referral_code':user.referral_code,
            }

            # Send OTP via email
            subject = 'Your OTP for Login'
            message = f'Your OTP for login is: {otp}'
            from_email = 'o23211671@gmail.com'
            print(otp)
            send_mail(subject, message, from_email, [user.email])

            return redirect(reverse('user:otpPage'))  # Redirect to OTP verification page
        else:
            messages.error(request, 'Registration failed. Please correct the errors in the form.')
    else:
        form = RegistrationForm()

    return render(request, 'user/user_registration.html', {'form': form})



def otpPage(request):
    error_message = None
    if request.method == 'POST':
        otp = request.POST.get('otp')
        otp_secret_key = request.session.get('otp_secret_key')
        otp_valid_date = request.session.get('otp_valid_date')

        # Verify the OTP
        if otp_secret_key and otp_valid_date is not None:
            valid_until = datetime.fromisoformat(otp_valid_date)

            # Check if the OTP is still valid
            if valid_until > datetime.now():
                totp = pyotp.TOTP(otp_secret_key, interval=60)
                current_otp=totp.now()
                #if totp.verify(otp):
                print(current_otp)
                if current_otp==otp:
                    print("OTP Verified")
                    user_details = request.session.get('user_details', {})
                    referrer_id = request.session.get('referrer_id')
                    if referrer_id is not None:
                        referrer=CustomUser.objects.get(id=referrer_id)
                        user = CustomUser(**user_details)
                        user.referrer=referrer
                        user.set_password(request.session.get('password'))
                        user.save()
                        login(request,user)
                        #user_wallet creation
                        user_wallet.objects.create(
                            user=request.user,
                            balance_amount=100,
                        )
                        #credit to referrar
                        referrer=CustomUser.objects.get(id=referrer_id)
                        referral_wallet=user_wallet.objects.get(user=referrer)
                        referral_wallet.balance_amount = referral_wallet.balance_amount + 100
                        referral_wallet.save()
                        del request.session['referrer_id']
                        messages.success(request,'₹100 credited to your wallet.')

                    else:
                        user = CustomUser(**user_details)
                        user.set_password(request.session.get('password'))
                        user.save()
                        login(request,user)
                        user_wallet.objects.create(
                            user=request.user
                        )

                    del request.session['user_details']
                    del request.session['otp_secret_key']
                    del request.session['otp_valid_date']
                    
                    # Redirect to the desired page
                    return redirect("home:homePage")
                else:
                    messages.error(request, 'Invalid OTP. Please try again.')
            else:
                messages.error(request, 'OTP has expired. Please request a new OTP.')
        else:
            messages.error(request, 'OTP verification failed. Please try again.')

    return render(request, 'user/otpPage.html')


def resendOtp(request):
    if request.method == "GET":
        # Generate a new OTP and update the session data
        totp = pyotp.TOTP(pyotp.random_base32(), interval=60)
        otp = totp.now()

        user_details = request.session['user_details']
        email = user_details.get('email', "None")
        subject = 'Your OTP for Login'
        message = f'Your OTP for login is: {otp}'
        from_email = 'o23211671@gmail.com'  
        print(f"Your new one-time password is {otp}")

        send_mail(subject, message, from_email, [email])
        request.session["otp_secret_key"] = totp.secret
        valid_date = datetime.now() + timedelta(seconds=60)
        request.session["otp_valid_date"] = str(valid_date)
        print(f"Your new one-time password is {otp}")
        return redirect("user:otpPage")

    return render(request, "registration/verify_otp.html")


@login_required(login_url='user:performlogin')
def perform_logout(request):
    logout(request)
    request.session.flush()
    request.session['user_logged_out'] = True
    return redirect('home:homePage')


@login_required(login_url='user:performlogin')
def user_profile(request):
    user_orders = order.objects.filter(user=request.user,payment=True)
    return render(request,'user/user_profile.html',{'user_orders':user_orders})

@login_required(login_url='user:performlogin')
def user_payment(request):
    user=request.user
    confirm_order =order.objects.filter(user=user,is_active=True,payment=False)
    return render(request,'user/user_payment.html',{'confirm_order':confirm_order})

@login_required(login_url='user:performlogin')
def user_cancel_rental(request,id):
    o=order.objects.get(id=id)
    o.status='cancelled'
    o.to_date=datetime.now()
    o.save()
    messages.error(request,'Rental cancelled')
    return redirect('user:user_payment')

@login_required(login_url='user:performlogin')
def user_invoice(request,id):
    ord=order.objects.filter(id=id)
    return render(request,'user/invoice.html',{'ord':ord})


def password_forget_maiil(request):
    if request.method=='POST':
        useremail=request.POST.get('useremail')
        try:
            user=CustomUser.objects.get(email=useremail)
            request.session['current_user']=useremail
            totp = pyotp.TOTP(pyotp.random_base32(), interval=60)
            otp = totp.now()
            request.session["otp_secret_key_for"] = totp.secret
            valid_date = datetime.now() + timedelta(seconds=60)
            request.session["otp_valid_date_for"] = str(valid_date)

            subject = 'Your OTP for Login'
            message = f'Your OTP for login is: {otp}'
            from_email = 'o23211671@gmail.com'

lyf/templates/user/user_edit.html
{% extends "homePage.html" %}
{% block content %}
<style>
    body {
        background-color: #ffffff;
    }

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #C1DCDC;
  overflow-x: hidden;
  padding-top: 20px;
  padding-top: 130px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 20px;
  color: black;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 20px; /* Increased text to enable scrolling */
  padding: 0px 50px 100px;
  padding-top: 20px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

.active {
    background-color: white;
}
</style>
</head>
<body>
    <!-- Sidebar -->

    <div class="sidenav">
        <a href="{% url 'user:user_profile' %}">User</a>
        <a href="{% url 'user:user_edit' %}" class="active">User Details</a>
        <a href="{% url 'user:user_payment' %}">Payments</a>
        <a href="{% url 'user:user_referral' %}">My Referrals</a>
    </div>
      
    <div class="main" style="margin-top: 8rem;">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <form  class="form" id="userEditForm" action="{% url 'user:user_edit' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="firstname">First Name</label>
                                <input class="form-control" type="text" name="firstname" maxlength="28"  value="{{ details.first_name|striptags|linebreaksbr }} ">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="lastname">Last Name</label>
                                <input class="form-control" type="text" name="lastname" maxlength="28" value="{{ details.last_name }}">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-12 col-sm-6 mb-3">
                    <div class="form-group">
                        <label for="mobile">Mobile Number</label>
                        <input class="form-control password-field" type="number" name="mobile" value="{{ details.phone_number }}">
                    </div>
                    <div class="form-group">
                        <label for="password1">New Password</label>
                        <input class="form-control password-field" type="password" name="password1" >
                    </div>
                    <div class="form-group">
                        <label for="password2">Confirm Password</label>
                        <input class="form-control password-field" type="password" name="password2" >
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col d-flex justify-content-end">
                    <button class="btn btn-primary" onsubmit="userEditForm()">Save Changes</button>
                </div>
            </div>
            
          </form>
    </div>

    <!-- Include Bootstrap JS (optional, if needed) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" ></script>
{% comment %} <script>
    
 function userEditForm() {
    console.log("hello")
    var form = document.getElementById('userEditForm');
    var firstNameInput = document.getElementById('firstname');
    var lastNameInput = document.getElementById('lastname');
    var mobileInput = document.getElementById('mobile');
    
    if (firstNameInput.value.length > 30) {
        console.log('entered')
        alert('First name must be 30 characters or less.');
        event.preventDefault(); // Prevent form submission
        return;
    }
    
    if (lastNameInput.value.length > 30) {
        alert('Last name must be 30 characters or less.');
        event.preventDefault(); // Prevent form submission
        return;
    }
    
    if (mobileInput.value.length > 30) {
        alert('Phone number must be 30 characters or less.');
        event.preventDefault(); // Prevent form submission
        return;
    }
    form.submit();
});
</script> {% endcomment %}
    
</body>
{% endblock %}

lyf/templates/user/user_payment.html
{% extends "homePage.html" %}
{% block content %}
<style>
    body {
        background-color: #ffffff;
    }

    .sidenav {
        height: 100%;
        width: 160px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #C1DCDC;
        overflow-x: hidden;
        padding-top: 20px;
        padding-top: 130px;
    }

    .sidenav a {
        padding: 8px 8px 8px 16px;
        text-decoration: none;
        font-size: 16px;
        color: black;
        display: block;
    }

    .sidenav a:hover {
        color: #f1f1f1;
    }

    .main {
        margin-left: 160px; /* Same as the width of the sidenav */
        font-size: 16px; /* Increased text to enable scrolling */
        padding: 0px 20px 100px;
        padding-top: 20px;
    }

    @media screen and (max-height: 450px) {
        .sidenav {padding-top: 15px;}
        .sidenav a {font-size: 14px;}
    }

    .active {
        background-color: white;
    }

    /* Additional styling for buttons */
    .btn-sm {
        padding: 5px 10px;
        font-size: 14px;
    }
</style>
</head>
<body>
    <!-- Sidebar -->
    <div class="sidenav">
        <a href="{% url 'user:user_profile' %}">User</a>
        <a href="{% url 'user:user_edit' %}">User Details</a>
        <a href="{% url 'user:user_payment' %}" class="active">Payments</a>
        <a href="{% url 'user:user_referral' %}">My Referrals</a>
    </div>

    <div class="main" style="margin-top: 8rem;">
        <div class="payment_area">
            <h4>User payment details</h4>
            {% if confirm_order %}
            <ul>
                {% for ord in confirm_order %}
                <li class="list-group-item shadow p-3 mb-3 bg-white rounded">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{{ ord.product.image.url }}" class="img-fluid rounded-start img-thumbnail" style="width: 100%; max-width: 150px; max-height: 100px;" alt="{{ cart_item.product.name }}">
                        </div>
                        <div class="col-md-8" style="padding-top: 40px;">
                            <h5 class="card-title">{{ ord.product.name }}</h5>
                            <div class="d-flex justify-content-between align-items-center">
                                Quantity:
                                <input type="number" class="form-control" value="{{ ord.quantity }}" style="width: 70px;" readonly>

                                Days required:
                                <input type="number" class="form-control" value="{{ ord.days_needed }}" style="width: 70px;" readonly>

                                <a href="{% url 'payments:make_payments' ord.id %}" class="btn btn-primary btn-sm">Make Payment</a>
                                <a href="{% url 'user:user_cancel_rental' ord.id %}" class="btn btn-danger btn-sm">Cancel Rental</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <h1>no payments</h1>
            {% endif %}
        </div>
    </div>

    <!-- Include Bootstrap JS (optional, if needed) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js" integrity="sha384-eMN5TJ4RZnZlfNlYKkHZcWSX9wOs4/sj7MK0WoFi9drQG5i1n94u

Kmpw/OiGKl2f" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyZqVNC8A4MZEtXGUoIfBZhddAp0EAAwEFE" crossorigin="anonymous"></script>
</body>
{% endblock %}

lyf/templates/user/user_profile.html
{% extends "homePage.html" %}
{% block content %}
<style>
    body {
        background-color: #ffffff;
    }

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #C1DCDC;
  overflow-x: hidden;
  padding-top: 20px;
  padding-top: 130px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 20px;
  color: black;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 20px; /* Increased text to enable scrolling */
  padding: 0px 50px 100px;
  padding-top: 20px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

.list-group-item {
    box-shadow: 1px 4px 8px rgba(0, 0, 0, 0.1); /* Adjust the shadow values as needed */
    margin-bottom: 15px; /* Adjust the margin as needed */
    background-color: #ffffff;
    border-radius: 1px;
}

small{
    font-size: 80%;
}

.active {
    background-color: white;
}

</style>
</head>
<body>

    <div class="sidenav">
        <a href="{% url 'user:user_profile' %}" class="active">User</a>
        <a href="{% url 'user:user_edit' %}">User Details</a>
        <a href="{% url 'user:user_payment' %}">Payments</a>
        <a href="{% url 'user:user_referral' %}">My Referrals</a>
    </div>
      
    <div class="main" style="margin-top: 8rem";>
    {% if messages %}
    <div class="modal" id="messageModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
    <div class="modal-header">
        {% for message in messages %}
        <h5>{{ message }}</h5><br>
        {% endfor %}
        <a href="{% url 'user:user_profile' %}">
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </a>
    </div>
    </div>
    </div>
    </div>

    <script>
    $(document).ready(function(){
    $('#messageModal').modal('show');
    });
    </script>
    {% endif %}
        <div class="profile-section">
            <h2>Welcome, {{ request.user.first_name }}!</h2>        
            <div id="payment" class="order-history">
                <ul class="list-group">
                    <h2>Order History</h2>
                    {% for order in user_orders %}
                        <li class="list-group-item">
                            <small>Product Name:</small> {{ order.product }}<br>
                            <small>Total Amount:</small> ₹{{ order.total_charges }}<br>
                            <img src="{{ order.product.image.url }}" alt="{{ order.product }}" class="thumbnail" style="float: right; margin-left: 10px; width: 70px; height: 70px;">

                            {% if order.cancelled_rental %}
                                <button class="btn btn-danger">Cancelled</button>
                            {% else %}
                                <small>Status:</small>{{ order.status }}<br>
                                <a href="{% url 'user:user_invoice' order.id %}" class="btn btn-dark">Invoice</a>
                            
                                {% if order.status == 'confirmed' or order.status == 'Taken' or order.status == 'Shipped' %}
                                    <a href="{% url 'payments:wallet_credit' order.id %}" class="btn btn-danger">Cancel Rental</a>
                                {% endif %}
                            {% endif %}
                        </li><br>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <!-- Include Bootstrap JS (optional, if needed) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js" integrity="sha384-eMN5TJ4RZnZlfNlYKkHZcWSX9wOs4/sj7MK0WoFi9drQG5i1n94uKmpw/OiGKl2f" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyZqVNC8A4MZEtXGUoIfBZhddAp0EAAwEFE" crossorigin="anonymous"></script>
</body>
{% endblock %}