lyf/cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('addToCart/<int:id>', views.addToCart,name='addToCart'),
    path('cartPage',views.cartPage,name='cartPage'),
    path('removeItemCart/<int:id>', views.removeItemCart,name='removeItemCart'),
    path('checkout',views.checkout,name='checkout'),
    path('addAddress',views.addAddress,name='addAddress'),
    path('delete_user_address/<int:id>', views.deleteUserAddress, name='deleteUserAddress'),
    path('updateCart',views.updateCart,name='updateCart'),
]

lyf/home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('', views.homePage,name='homePage'),
    path('searchbar',views.searchbar,name='searchbar'),
    path('contactus',views.contactus,name='contactus'),
] 

lyf/lyf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace='home')),
    path('',include('products.urls',namespace='products')),
    path('',include('user.urls',namespace='user')),
    path('',include('adminPanel.urls',namespace='adminPanel')),
    path('',include('provider.urls',namespace='provider')),
    path('',include('cart.urls',namespace='cart')),
    path('',include('order.urls',namespace='order')),
    path('',include('payments.urls',namespace='payments')),
    path('paypal/', include('paypal.standard.ipn.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyf/payments/urls.py
from django.urls import path
from . import views
from paypal.standard.ipn import views as paypal_ipn_views

app_name='payments'
urlpatterns = [
    path('payments/<int:id>',views.make_payments,name='make_payments'),
    path('payment_done/<int:id>',views.payment_done,name='payment_done'),
    path('payment_cancelled',views.payment_cancelled,name='payment_cancelled'),
    path('make_payments/<int:id>/',views.make_payments,name='make_payments'),
    path('final_pay/<int:id>',views.final_pay,name='final_pay'),
    path('wallet',views.wallet,name='wallet'),
    path('wallet_credit/<int:id>/',views.wallet_credit,name='wallet_credit'),
    path('payment_selection/<int:id>',views.payment_selection,name='payment_selection'),
    path('wallet_debit/<int:id>',views.wallet_debit,name='wallet_debit'),
    path('provider_pay/<int:id>/', views.provider_pay, name='provider_pay'),
]

lyf/user/urls.py
from django.urls import path
from . import views

app_name='user'
urlpatterns = [
    path('performlogin', views.performlogin,name='performlogin'),
    path('user_registration', views.user_registration,name='user_registration'),
    path('otpPage',views.otpPage,name='otpPage'),
    path('perform_logout',views.perform_logout,name='perform_logout'),
    path('resendOtp',views.resendOtp,name='resendOtp'),
    path('user_profile/',views.user_profile,name='user_profile'),
    path('user_payment',views.user_payment,name='user_payment'),
    path('user_cancel_rental/<int:id>',views.user_cancel_rental,name='user_cancel_rental'),
    path('user_invoice/<int:id>',views.user_invoice,name='user_invoice'),
    path('password_forget_maiil', views.password_forget_maiil, name='password_forget_maiil'),
    path('forgot_otp_verify',views.forgot_otp_verify,name='forgot_otp_verify'),
    path('password_change',views.password_change,name='password_change'),
    path('user_edit',views.user_edit,name='user_edit'),
    path('user_referral',views.user_referral,name='user_referral'),
]

lyf/templates/contactus.html
{% extends "homePage.html" %}
{% load static %}
{% block content %}

    <div class="text_container" style="margin-top: 8rem;" >
        <h1>Email Us</h1>
        <h1 class="email">lyfrentals04@gmail.com</h1>
    </div>


{% endblock %}

lyf/templates/homePage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static "image/icon.png" %}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>


    <title>lyf Rentals</title>
    
</head>
    <body> 
    <header>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container-fluid">
    <div class="navbar-brand">
    <a href="{% url 'home:homePage' %}">
    <img src="{% static 'image/logo.png' %}" alt="Logo" class="logo hover">
    </a>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item">
    {% if query %}
    <form class="form-inline" method="get" action="{% url 'home:searchbar' %}">
    <div class="input-group">
    <input class="form-control custom-size-input" type="search" aria-label="Search" name="q"
        value="{{ query }}">
    <button type="submit" class="btn" style="background-color: #DCECEC;">
        <img src="{% static 'image/Search.svg' %}" alt="Search Icon" class="search-icon">
    </button>
    </div>
    </form>
    {% else %}
    <form class="form-inline" method="get" action="{% url 'home:searchbar' %}">
    <div class="input-group">
    <input class="form-control custom-size-input" type="search" placeholder="Search"
        aria-label="Search" name="q">
    <button type="submit" class="btn" style="background-color: #DCECEC;">
        <img src="{% static 'image/Search.svg' %}" alt="Search Icon" class="search-icon">
    </button>
    </div>
    </form>
    {% endif %}
    </li>
    </ul>

    <ul class="navbar-nav ms-auto">
    <li class="nav-item hover">
    <a class="nav-link" href="{% url 'payments:wallet' %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-wallet" viewBox="0 0 16 16">
    <path d="M0 3a2 2 0 0 1 2-2h13.5a.5.5 0 0 1 0 1H15v2a1 1 0 0 1 1 1v8.5a1.5 1.5 0 0 1-1.5 1.5h-12A2.5 2.5 0 0 1 0 12.5zm1 1.732V12.5A1.5 1.5 0 0 0 2.5 14h12a.5.5 0 0 0 .5-.5V5H2a2 2 0 0 1-1-.268M1 3a1 1 0 0 0 1 1h12V2H2a1 1 0 0 0-1 1"/>
    </svg>
    </a>
    </li>
    <li class="nav-item hover">
    <a class="nav-link" href="{% url 'cart:cartPage' %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
    </svg>
    </a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item dropdown hover">
    <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false">
    Account
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="{% url 'user:user_profile' %}">My Profile</a>
    <a class="dropdown-item" href="{% url 'home:contactus' %}">Contact us</a>
    <a class="dropdown-item" id="logout_btn">Logout</a>
    </div>
    </li>
    {% else %}
    <li class="nav-item hover">
    <a class="nav-link" href="{% url 'user:performlogin' %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
    </svg>
    </a>
    </li>
    {% endif %}
    <li class="nav-item hover">
    <a class="nav-link" href="{% url 'provider:providerPanel' %}">Become a Provider</a>
    </li>
    </ul>
    </div>
    </div>
    </nav>

    </header>
    {% block content %}
        <div class="container-fluid" style="margin-top: 8rem;">
            {% if messages %}
            <div class="modal" id="messageModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                {% for message in messages %}
                <h5>{{ message }}</h5><br>
                {% endfor %}
                <a href="{% url 'home:homePage' %}">
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </a>
            </div>
            </div>
            </div>
            </div>

            <script>
            $(document).ready(function(){
            $('#messageModal').modal('show');
            });
            </script>
            {% endif %}
            
            {% if products%}
            <div class="row">
                {% for product in products %}
                <div class="col-md-3 col-sm-6 mb-4 mt-6">
                    <div class="card border shadow hover" style="width: 250px; height: 450px; background-color: #FFFFFF;">
                        <img class="card-img-top border-bottom p-3 rounded-top" style="width: 100%; height: 60%; object-fit: cover;" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'image/placeholder_image.jpg' %}{% endif %}" alt="Product Image">
                        <div class="card-body">
                            <a href="{% url 'products:productPage' product.id %}">
                                <h5 class="card-title">{{ product.title }}</h5>
                            </a>
                            <p class="card-text">{{ product.description | slice:":25" }}...</p>
                            <!-- Add to Cart Button -->
                            <form method="post" action="{% url 'cart:addToCart' product.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ product.id }}">
                                <button type="submit" class="btn btn-secondary">Add to Cart</button><br>
                                <p><small>Delivery at <strong>10km radius</strong></small></p>
                            </form>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div> 
            {% else %}
                <h3>No products Found</h3>
            {% endif %}
        </div>

        <footer class="bg-light py-4">
            <div class="container">
                <div class="row">
                    <!-- First Column -->
                    <div class="col-md-3">
                        <h5 style="color: black; font-size: 18px; font-family: Shrikhand; font-weight: 400; word-wrap: break-word">lyf</h5>
                        <p style="color: rgba(30, 30, 30, 0.50); font-size: 18px; font-family: Poppins; font-weight: 500; word-wrap: break-word">Rent smart, Anytime, Anywhere</p>
                    </div>
        
                    <!-- Second Column -->
                    <div class="col-md-3">
                        <h5 class="text-dark">Information</h5>
                        <p class="text-muted">About</p>
                        <p class="text-muted">Product</p>
                        <p class="text-muted">Blog</p>
                    </div>
        
                    <!-- Third Column -->
                    <div class="col-md-3">
                        <h5 class="text-dark">Company</h5>
                        <p class="text-muted">Community</p>
                        <p class="text-muted">Career</p>
                        <p class="text-muted">Our story</p>
                    </div>
        
                    <!-- Fourth Column -->
                    <div class="col-md-3">
                        <h5 class="text-dark">Contact</h5>
                        <p class="text-muted">Getting Started</p>
                        <p class="text-muted">Pricing</p>
                        <p class="text-muted">Resources</p>
                    </div>
                </div>
        
                <!-- Copyright Section -->
                <div class="row mt-4">
                    <div class="col-md-12 text-center">
                        <p style="color: rgba(30, 30, 30, 0.50); font-size: 18px; font-family: Poppins; font-weight: 500; word-wrap: break-word">
                            LYF RENTALS :- 2024
                        </p>
                    </div>
                </div>
            </div>
        </footer> 
    
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function(){
            // Show dropdown after clicking the toggle
            $(".nav-item.dropdown").on("click", function(){
                $(this).find(".dropdown-menu").addClass("show");
            });
            $('#logout_btn').on('click', function(){
                Swal.fire({
                    position: "center-center",
                    icon: "success",
                    title: "You are successfully logged out",
                    showConfirmButton: false,
                    timer: 1500
                }).then(() => {
                    window.location.href = '{% url "user:perform_logout" %}';
                });
                // You can add your logout logic here
            });
            
        });
    </script>
</body>
</html>

lyf/templates/test.html
hello